version: '3.1'
services:
    nginx:
        image: nginx:1.13.7
        container_name: nginx
        depends_on:
            - flask
        volumes:
#            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - ../../../letsencrypt-docker-nginx/src/production://usr/share/nginx/html
            - ./production.conf:/etc/nginx/conf.d/default.conf
            - ./dh-param/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
            - ./docker-volumes/etc/letsencrypt/live/bl4ckb0x.ddnss.de/fullchain.pem:/etc/letsencrypt/bl4ckb0x.ddnss.de/fullchain.pem
            - ./docker-volumes/etc/letsencrypt/live/bl4ckb0x.ddnss.de/privkey.pem:/etc/letsencrypt/live/bl4ckb0x.ddnss.de/privkey.pem
        networks:
            - my-network
        ports:
            - "80:80"
            - "443:443"
    flask:
        build:
            context: ./
            dockerfile: Dockerfile
        image: flask:latest
        container_name: flask
        volumes:
            - ./code:/code/
            - ./templates:/templates/
            - ./testdb:/db/testdb
        environment:
            - FLASK_APP=/code/server.py
        command: flask run --host=0.0.0.0
        networks:
            my-network:
networks:
    my-network:
        driver: bridge
